import { supabase } from '../services/supabase';
import { sendToMakeWebhook } from '../services/make';
import { Transaction, Lead } from '../types';

/**
 * Agent C: The Analyst
 * Job: Monitors Google Sheets / Supabase transactions. generates reports.
 */

export class AnalystAgent {
  
  async sendDailyClosingReport(dailyTransactions: Transaction[], dailyLeads: Lead[], adminEmail: string) {
    console.log('[Agent C: Analyst] Generating End of Day Closing Report...');

    try {
      const todayDate = new Date().toISOString().split('T')[0];
      const checkIns = dailyTransactions.filter(t => t.check_in_date === todayDate);
      const checkOuts = dailyTransactions.filter(t => t.check_out_date === todayDate);
      const totalRevenue = dailyTransactions.reduce((sum, tx) => sum + (tx.amount || 0), 0);

      const guestDetails = dailyTransactions.map(tx => {
          const lead = dailyLeads.find(l => String(l.id) === String(tx.lead_id));
          return `- Room ${tx.room_number}: ${lead?.name || 'Unknown'} (${lead?.company || 'N/A'}). Amount: $${tx.amount}. Status: ${tx.status}`;
      }).join('\\n');

      const reportBody = `Daily Closing Report for Hotel Fountain - ${todayDate}\\n\\n` +
       `Total Transactions Today: ${dailyTransactions.length}\\n` +
       `Total Revenue Today: $${totalRevenue}\\n` +
       `Check-Ins Today: ${checkIns.length}\\n` +
       `Check-Outs Today: ${checkOuts.length}\\n\\n` +
       `Guest & Room Activity:\\n${guestDetails}\\n\\n` +
       `Report generated by Antigravity Sales Engine.`;

      console.log('--- Sales Engine Analysis Report ---');
      console.log(reportBody.replace(/\\n/g, '\\n'));
      console.log('------------------------------------');

      console.log(`[Agent C: Analyst] Pinging Make.com to send Daily Closing Report to ${adminEmail}...`);
      await sendToMakeWebhook({
          action: 'send_email',
          lead_email: adminEmail,
          subject: `Hotel Fountain - Daily Closing Report [${todayDate}]`,
          body: reportBody.replace(/\\n/g, '\n') // Make format
      });

    } catch (error) {
      console.error('[Agent C: Analyst] Failed to send Daily Report:', error);
    }
  }
}
